{% set version = '1.3.8.1.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-genetics
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/genetics_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/genetics/genetics_{{ version }}.tar.gz
  sha256: 30cb67de2e901578fd802deb7fbfea6c93024c9fb6ea66cad88430a3a2a51eec

build:
  merge_build_host: True  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-combinat
    - r-gdata
    - r-gtools
    - r-mvtnorm
  run:
    - r-base
    - r-mass
    - r-combinat
    - r-gdata
    - r-gtools
    - r-mvtnorm

test:
  commands:
    - $R -e "library('genetics')"           # [not win]
    - "\"%R%\" -e \"library('genetics')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=genetics
  license: GPL
  summary: Classes and methods for handling genetic data. Includes classes to represent genotypes
    and haplotypes at single markers up to multiple markers on multiple chromosomes.
    Function include allele frequencies, flagging homo/heterozygotes, flagging carriers
    of certain alleles, estimating and testing for Hardy-Weinberg disequilibrium, estimating
    and testing for linkage disequilibrium, ...
  license_family: GPL
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: genetics
# Title: Population Genetics
# Version: 1.3.8.1.2
# Date: 2012-11-26
# Author: Gregory Warnes, with contributions from Gregor Gorjanc, Friedrich Leisch, and Michael Man.
# Maintainer: Gregory Warnes <greg@warnes.net>
# Depends: combinat, gdata, gtools, MASS, mvtnorm
# Description: Classes and methods for handling genetic data. Includes classes to represent genotypes and haplotypes at single markers up to multiple markers on multiple chromosomes. Function include allele frequencies, flagging homo/heterozygotes, flagging carriers of certain alleles, estimating and testing for Hardy-Weinberg disequilibrium, estimating and testing for linkage disequilibrium, ...
# License: GPL
# Packaged: 2019-04-21 11:05:10 UTC; ripley
# Repository: CRAN
# Date/Publication: 2019-04-22 06:57:07 UTC
# NeedsCompilation: no
