appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: d8cV1IqHiHeVR53a/eAMdXlZznQGEMgmZ/YfyO8NXTuTklk8T9smq3Q9GqVhx6C2k5XJYZJCpTqev6SdTVjYyr9aPLUO1zi0lt62ZUSMGmJkHC/RVI/z5T/NVBQGXf3Jtnz+GOuEjE3X2H664yYGVeBGRQ6N7blv8qpbMF/gC0QcPvkxyL37VZHl5JRIjTzjFCuGQ7jznvGNJfoMvqvr6LJXvAoAcyBenAhu9s9Wf6QybTCuAi7HI7rVgJUtDm3CyJnk4mr2w2AQjDkFQlJTNIR6s74CwbPLQLGyigGBGCXNCe3yYeJTG81YgKu7pyD44m6XDdtmImNTRksCaUL8YeRC6yQ0aQt7ttl/ju+LitKK+9tOQx1cbuGMhfrw6XP6Dc2fn7RICYwJMzkF10wuVThGX1t3YocEAinxPdmbUNd96dYkz7syTnjoPFAGqBHdZdqXQIve6KSoVSOoOG9ZLgepzAV1Zsf5pAHE3QIpfsADa/mXzK56Mvd9zZ7o/13Y25YitaXWhB33Ayfat5s0cSPru0MVt1WW1zfmhm4xigf35hWycrhdlw1AmYEEY/Cd52auI9FnxXUXrLp8Ig8035SO0oUYamKyIlAkvnSJqqZGLnCuOd19XWQ/oU499FnIqxzicdh3puR0aE6RkEB0yZW18Uv2NN8CWUrYeg5V7KM=}
