travis:
  secure:
    BINSTAR_TOKEN: faitibQxYuCguHf+r7TykvMovhctoLvFXxg8/mbA3WTnIsppDxS16yTegO/u3tKelf9m7ngkyHNphb6j97a8RFu3XjeUdYFLzaNxOiagEgFfvr7KcVvOAorzoCpA8gwyq0xHs0nflypdvI5oraJGJ9nb97GcuUFrGiQDGlz2iKq2CiGzDPdyXJhfrXxnGPqa4AQIN9shfc7JE5rCVQQDVPTkeGsDThlio4Fpm2CfWtsdr9DUlD8Eggr6p3zoxkvDUSjc/9NONNypEbFHUzbhhFZe3A2htFubE+hJPXyCkYexdO2aYZOUPUK341QgXwykTm+QeTcf9+i84MLCjznoauENSVhdJE47blaAMPk2wOKUYFVmM9vozjbKqXBi75zsAMmQtSc0USRkyy6KJ47qb5eiQMoLsb+IwhwY1c5uP5ghYMj+RiC3uGh0CQLdwefcK42vCAuKbPmTl9mXN5jwrFlCKQXc+VhRAB6ONzOIiCodr4I7JD+HmevNOaJ1xjVNICTmBP/Aa1AdzpVWgBZhLsfCh+aJGnTftZ3LHJep07WyYkeMYOhZ58NYvNI594TlV2p8L6v9Eq1BD6JNpEffVFx9ZLeF8EGnWMHyLzFz7s2tXPcnw58Y6YO7fOToVRV6XxeQtXMQOvIek243FGi68+81an++GzMWQoMHNDo4fVo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
